name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run ci:test -- --coverage
      - name: Codecov
        uses: codecov/codecov-action@v4.0.0-beta.3
        with:
          name: Coverage report
          token: ${{ secrets.CODE_COVERAGE_TOKEN }}
          directory: coverage/
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
